// <auto-generated />
using System;
using Jurigest.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jurigest.Persistence.Migrations
{
    [DbContext(typeof(JurigestDbContext))]
    [Migration("20260826171425_CrearCatalogosTribunalesAbogadosYDiligenciasEncargadas")]
    partial class CrearCatalogosTribunalesAbogadosYDiligenciasEncargadas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Jurigest.Domain.Judicial.Catalogos.AbogadoCatalogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Abogados", (string)null);
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Catalogos.ComunaCatalogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Comunas", (string)null);
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Catalogos.DiligenciaEncargadaCatalogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("CodigoTipoDiligencia")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoTipoDiligencia");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("DiligenciasEncargadas", (string)null);
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Catalogos.ReceptorJudicialCatalogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("ReceptoresJudiciales", (string)null);
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Catalogos.TipoCausaCatalogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposCausa", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Activo = true,
                            Codigo = "C",
                            FechaCreacion = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Civil"
                        });
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Catalogos.TipoDiligenciaCatalogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("CodigoSistema")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoSistema")
                        .IsUnique()
                        .HasFilter("[CodigoSistema] IS NOT NULL");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposDiligencia", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Activo = true,
                            CodigoSistema = 1,
                            FechaCreacion = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Notificación"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Activo = true,
                            CodigoSistema = 2,
                            FechaCreacion = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Requerimiento de pago"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Activo = true,
                            CodigoSistema = 3,
                            FechaCreacion = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Embargo"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Activo = true,
                            CodigoSistema = 4,
                            FechaCreacion = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Lanzamiento"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Activo = true,
                            CodigoSistema = 5,
                            FechaCreacion = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Retiro de exhorto"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Activo = true,
                            CodigoSistema = 6,
                            FechaCreacion = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Retiro de expediente"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Activo = true,
                            CodigoSistema = 7,
                            FechaCreacion = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Incautación"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Activo = true,
                            CodigoSistema = 8,
                            FechaCreacion = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Protesto"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Activo = true,
                            CodigoSistema = 9,
                            FechaCreacion = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Citación"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000099"),
                            Activo = true,
                            CodigoSistema = 99,
                            FechaCreacion = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Otro"
                        });
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Catalogos.TribunalCatalogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Tribunales", (string)null);
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Entities.Causa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroRol")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Rit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("TipoCausaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tribunal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TipoCausaId");

                    b.HasIndex("TipoCausaId", "NumeroRol");

                    b.ToTable("Causas", (string)null);
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Entities.Diligencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CausaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comuna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRealizada")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceptorJudicial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CausaId");

                    b.ToTable("Diligencias", (string)null);
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Entities.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CausaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CausaId");

                    b.ToTable("Documentos", (string)null);
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Entities.Resolucion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CausaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CausaId");

                    b.ToTable("Resoluciones", (string)null);
                });

            modelBuilder.Entity("Jurigest.Domain.Seguridad.Entities.AuditoriaSeguridad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UsuarioActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UsuarioAfectadoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FechaUtc");

                    b.HasIndex("UsuarioActorId");

                    b.HasIndex("UsuarioAfectadoId");

                    b.ToTable("AuditoriasSeguridad", (string)null);
                });

            modelBuilder.Entity("Jurigest.Domain.Seguridad.Entities.SesionUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("ExpiraUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReemplazadaPorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("RevocadaUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VersionSeguridad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId", "RevocadaUtc");

                    b.ToTable("SesionesUsuario", (string)null);
                });

            modelBuilder.Entity("Jurigest.Domain.Seguridad.Entities.TokenRecuperacionPassword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiraUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevocadoUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UsadoUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId", "ExpiraUtc");

                    b.ToTable("TokensRecuperacionPassword", (string)null);
                });

            modelBuilder.Entity("Jurigest.Domain.Seguridad.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("BloqueadoHastaUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<int>("VersionSeguridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Entities.Diligencia", b =>
                {
                    b.HasOne("Jurigest.Domain.Judicial.Entities.Causa", null)
                        .WithMany("Diligencias")
                        .HasForeignKey("CausaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Entities.Documento", b =>
                {
                    b.HasOne("Jurigest.Domain.Judicial.Entities.Causa", null)
                        .WithMany()
                        .HasForeignKey("CausaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Entities.Resolucion", b =>
                {
                    b.HasOne("Jurigest.Domain.Judicial.Entities.Causa", null)
                        .WithMany()
                        .HasForeignKey("CausaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jurigest.Domain.Seguridad.Entities.SesionUsuario", b =>
                {
                    b.HasOne("Jurigest.Domain.Seguridad.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jurigest.Domain.Seguridad.Entities.TokenRecuperacionPassword", b =>
                {
                    b.HasOne("Jurigest.Domain.Seguridad.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Entities.Causa", b =>
                {
                    b.Navigation("Diligencias");
                });
#pragma warning restore 612, 618
        }
    }
}
