// <auto-generated />
using System;
using Jurigest.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jurigest.Persistence.Migrations
{
    [DbContext(typeof(JurigestDbContext))]
    [Migration("20260714011748_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Jurigest.Domain.Judicial.Entities.Causa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Causas", (string)null);
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Entities.Diligencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Completada")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EncargoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EncargoId");

                    b.ToTable("Diligencia");
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Entities.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EncargoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EncargoId");

                    b.ToTable("Documento");
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Entities.Encargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CausaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CausaId")
                        .IsUnique();

                    b.ToTable("Encargo");
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Entities.Resolucion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EncargoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EncargoId");

                    b.ToTable("Resolucion");
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Entities.Causa", b =>
                {
                    b.OwnsOne("Jurigest.Domain.Judicial.ValueObjects.RolUnicoTribunal", "Rit", b1 =>
                        {
                            b1.Property<Guid>("CausaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("Rit");

                            b1.HasKey("CausaId");

                            b1.ToTable("Causas");

                            b1.WithOwner()
                                .HasForeignKey("CausaId");
                        });

                    b.Navigation("Rit")
                        .IsRequired();
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Entities.Diligencia", b =>
                {
                    b.HasOne("Jurigest.Domain.Judicial.Entities.Encargo", null)
                        .WithMany("Diligencias")
                        .HasForeignKey("EncargoId");
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Entities.Documento", b =>
                {
                    b.HasOne("Jurigest.Domain.Judicial.Entities.Encargo", null)
                        .WithMany("Documentos")
                        .HasForeignKey("EncargoId");
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Entities.Encargo", b =>
                {
                    b.HasOne("Jurigest.Domain.Judicial.Entities.Causa", null)
                        .WithOne("Encargo")
                        .HasForeignKey("Jurigest.Domain.Judicial.Entities.Encargo", "CausaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Entities.Resolucion", b =>
                {
                    b.HasOne("Jurigest.Domain.Judicial.Entities.Encargo", null)
                        .WithMany("Resoluciones")
                        .HasForeignKey("EncargoId");
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Entities.Causa", b =>
                {
                    b.Navigation("Encargo");
                });

            modelBuilder.Entity("Jurigest.Domain.Judicial.Entities.Encargo", b =>
                {
                    b.Navigation("Diligencias");

                    b.Navigation("Documentos");

                    b.Navigation("Resoluciones");
                });
#pragma warning restore 612, 618
        }
    }
}
